//! 全部 Tauri 命令的注册表。
//!
//! 一个 Tauri 应用只能有**一处** `.invoke_handler()`——`generate_handler!` 返回的是
//! 不可组合的匿名闭包，无法从多次宏调用拼出来。因此全部命令集中在此文件，
//! 按领域用注释分组，保持"一处看全"。
//!
//! `generate_handler!` 内的路径在**调用点**展开，所以顶部这行 `use` 把
//! `api::` / `ai_service::` 等拉到本模块作用域，使下面 234 行清单与原先在
//! `lib.rs` 中逐字一致（无需改成 `ling_chat_main::api::…`）。
//!
//! 注意：`exit_app` 定义在本文件末尾而非 `api/`。这是对「command 放 api/」约定的
//! 有意例外——它是进程生命周期命令，没有对应的 `config/` 业务逻辑，且与注册表
//! 同文件时可保持清单里的裸 `exit_app` 条目不变。

use ling_chat_main::{ai_service, api, cast, lan_sync, resource_sync, utils, world_map};
use ling_chat_plugins as plugins;

/// 把全部命令注册到 `builder` 上。
pub fn register(builder: tauri::Builder<tauri::Wry>) -> tauri::Builder<tauri::Wry> {
    // 注册所有 API 命令
    builder.invoke_handler(tauri::generate_handler![
        // ══════════ 世界模拟（地图系统）══════════
        // ⚠️ 前缀不是装饰：`#[tauri::command]` 除了函数本体，还会在**定义它的模块里**
        // 生成 `pub use {__cmd__xxx, __tauri_command_name_xxx}`，
        // `generate_handler!` 就是拿这条路径去找宏的。所以凡是命令定义在子模块里的，
        // 都必须写全路径（`world_map::live::world_map_location`），
        // 写短成 `world_map::world_map_location` 会在编译期直接 E0433（本项目踩过）。
        world_map::world_map_blocks,
        world_map::world_map_blocks_at,
        world_map::world_map_geo_status,
        world_map::world_map_coord_selftest,
        world_map::world_map_render_svg,
        world_map::world_map_push_events,
        world_map::world_map_recent_events,
        // ── 真源 world_map_rs 模块搬入后新暴露的命令 ──
        world_map::world_map_render,
        world_map::world_map_geo_svg,
        world_map::world_map_stats,
        world_map::world_map_maplib_stats,
        world_map::world_map_maplib_list,
        world_map::world_map_maplib_cleanup,
        // P5-4：离线可用清单（纯读本地：geo 缓存 + 地图库 + 布局缓存）
        world_map::world_map_offline_available,
        world_map::world_map_schedule,
        world_map::world_map_transport_plan,
        world_map::world_map_osm_summary,
        world_map::world_map_time,
        // ── T2-1：生活设施（7 类）。组件 `WsFacilityLayer` 优先走这三条命令，
        //    浏览器预览走调试服务 8791 的 `/api/facilities`；两条路都不通时**如实显示取不到**，
        //    不画假点（T2-1 卡的硬要求）。──
        world_map::world_map_facilities,
        world_map::world_map_facilities_types,
        world_map::world_map_facility_at,
        // ── T2-2：交通站点（公交/地铁/停车…），供 `WsTransitLayer` 把上下车点吸附到真实站点 ──
        world_map::world_map_transport_nodes,
        // ── 真 2.5D 楼房（OSM 建筑轮廓 + 楼高）。浏览器通路走调试服务的 `/api/buildings`，
        //    真壳走这条命令。⚠️ 数据质量实测：OSM 楼高覆盖率只有 13~18%，其余回落默认 8m
        //    （见 world_map/PROJECT-STATE.md 的覆盖率表；要真实天际线需引 Overture/Cesium）。──
        world_map::world_map_buildings,
        // ── 应用内实时绘制（Channel 版；浏览器/调试服务的 SSE 路并存）──
        world_map::bridge::world_map_district_stream,
        world_map::bridge::world_map_district_stream_cancel,
        // ── 实时数据：定位 / 天气（前端 worldMapApi.location / .weather）──
        world_map::live::world_map_location,
        world_map::live::world_map_weather,
        // ── 世界模拟运行时状态（P3：前端推状态 / 读状态）──
        world_map::state::world_map_update_runtime,
        world_map::state::world_map_runtime,
        // ── 世界模拟移动状态机（P4：AI 位置指令 → 角色在地图上移动）──
        world_map::move_cmd::world_map_trip_status,
        world_map::move_cmd::world_map_trip_start,
        world_map::move_cmd::world_map_trip_cancel,
        world_map::move_cmd::world_map_trip_speedup,
        // ── 世界模拟现实事件引擎（P5-2/P5-3：驱动器 / 读最近事件 / 待写记忆）──
        // ⚠️ 待写记忆两条路：`world_map_pending_memory` 是**只读预览**（前端用），
        //    `world_map_take_pending_memory` 是 drain（记忆管线用）。
        //    消费权裁定见 `event_cmd.rs::world_map_pending_memory` 的注释。
        world_map::event_cmd::world_map_tick,
        world_map::event_cmd::world_map_events_recent,
        world_map::event_cmd::world_map_pending_memory,
        world_map::event_cmd::world_map_take_pending_memory,
        // ── 城市级**真拼接**大图（T5-1：区县街区图按经纬度拼成一张大 SVG）──
        // 与 `world_map_geo_svg`（行政区划总览）是两件事，不互相替代。
        world_map::stitch_cmd::world_map_bigmap_svg,
        world_map::stitch_cmd::world_map_bigmap_plan,
        utils::log_bridge::get_log_history,
        utils::log_bridge::open_log_window,
        utils::log_bridge::is_log_window_open,
        plugins::commands::plugin_list,
        plugins::commands::plugin_set_enabled,
        plugins::commands::plugin_save_config,
        plugins::commands::plugin_reload,
        plugins::commands::plugin_delete,
        plugins::commands::plugin_resources,
        plugins::commands::plugin_resource_hide,
        plugins::commands::plugin_resource_restore,
        plugins::commands::plugin_resource_keep,
        plugins::commands::import_plugin_from_path,
        plugins::commands::cancel_plugin_import,
        api::settings::get_settings_tree,
        api::settings::save_settings,
        api::settings::get_setting_by_key,
        api::settings::select_file,
        api::settings::list_llm_providers,
        api::settings::save_llm_provider,
        api::settings::delete_llm_provider,
        #[cfg(target_os = "windows")]
        api::settings::set_hdr_mode,
        api::settings::set_llm_role,
        api::settings::switch_llm,
        api::settings::test_llm_provider,
        api::settings::list_llm_models,
        api::codex::codex_auth_status,
        api::codex::codex_start_login,
        api::codex::codex_poll_login,
        api::codex::codex_logout,
        api::codex::codex_get_quota,
        api::font::list_system_fonts,
        api::font::import_font,
        api::font::list_imported_fonts,
        api::font::delete_imported_font,
        api::character::get_character_list,
        api::character::get_role_info,
        api::character::get_role_settings,
        api::character::get_character_file,
        api::character::get_avatar_file,
        api::character::select_clothes,
        api::character::update_role_settings,
        api::character::delete_character,
        api::character::open_characters_folder,
        api::live2d::import_live2d,
        api::live2d::get_live2d_file,
        api::live2d::inspect_live2d,
        api::live2d::get_live2d_variant_assets,
        api::background::get_background_list,
        api::background::get_background_file,
        api::background::upload_background_image,
        api::background::open_backgrounds_folder,
        api::background::list_background_categories,
        api::background::create_background_category,
        api::background::delete_background_category,
        api::scene::list_scenes,
        api::scene::create_scene,
        api::scene::update_scene,
        api::scene::delete_scene,
        api::scene::select_scene,
        api::scene::set_scene_awareness,
        api::scene::clear_empty_scenes,
        api::scene::move_scene_to_category,
        api::music::get_music_list,
        api::music::get_music_file,
        api::music::upload_music,
        api::music::delete_music,
        api::music::save_bgm_state,
        api::music::list_music_categories,
        api::music::create_music_category,
        api::music::delete_music_category,
        api::music::open_music_folder,
        api::locale::get_locale_messages,
        api::ambient::get_ambient_list,
        api::ambient::upload_ambient,
        api::ambient::delete_ambient,
        api::ambient::save_ambient_state,
        api::asset::get_asset_base64,
        api::asset::get_voice_audio,
        api::game::init_game,
        api::game::select_character,
        api::game::clear_conversation,
        api::game::reactivate_tts,
        api::game::clear_tts_cache,
        api::game::update_voice_lang,
        api::game::get_tts_cache_info,
        api::game::add_role_to_scene,
        api::game::remove_role_from_scene,
        api::game::notify_player_entry,
        api::memory::get_memory_debug_overview,
        api::memory::get_role_memory_snapshot,
        api::affection::get_affection,
        api::chat::send_chat_message,
        api::chat::send_system_message,
        api::chat::rollback_conversation,
        api::chat::generate_line_voice,
        api::chat::feed_image,
        api::chat::feed_text,
        api::screenshot::start_screenshot,
        api::screenshot::get_overlay_data,
        api::screenshot::confirm_screenshot,
        api::screenshot::cancel_screenshot,
        api::save::list_saves,
        api::save::create_save,
        api::save::load_save,
        api::save::update_save,
        api::save::delete_save,
        api::save::update_save_title,
        api::save::save_screenshot,
        api::save::capture_main_window_screenshot,
        api::script::list_scripts,
        api::script::list_standalone_scripts,
        api::script::start_script,
        api::script::script_submit_input,
        api::script::script_submit_choice,
        // ── 剧本编辑器 ──
        api::script_editor::editor_get_schema,
        api::script_editor::editor_list_scripts,
        api::script_editor::editor_read_script,
        api::script_editor::editor_read_chapter,
        api::script_editor::editor_validate_script,
        api::script_editor::editor_write_chapter,
        api::script_editor::editor_write_story_config,
        api::script_editor::editor_create_chapter,
        api::script_editor::editor_delete_chapter,
        api::script_editor::editor_delete_character,
        api::script_editor::editor_create_script,
        api::script_editor::editor_delete_script,
        api::script_editor::editor_upload_asset,
        api::script_editor::editor_upload_editor_bg,
        api::script_editor::editor_upload_editor_bg_data,
        api::script_editor::editor_create_character,
        api::script_editor::editor_list_global_assets,
        api::script_editor::editor_list_asset_files,
        api::script_editor::editor_delete_asset,
        api::script_editor::editor_rescan_scripts,
        api::script_editor::editor_start_preview,
        api::script_editor::editor_preview_readiness,
        api::script_editor::editor_list_global_characters,
        api::script_editor::editor_import_global_character,
        api::script_editor::editor_stop_preview,
        api::script_editor::editor_open_script_folder,
        // ── 剧本编辑器 · AI 助手（Skill Agent）──
        api::script_editor::agent::editor_agent_get_settings,
        api::script_editor::agent::editor_agent_save_settings,
        api::script_editor::agent::editor_agent_get_default_dirs,
        api::script_editor::agent::editor_agent_list_skills,
        api::script_editor::agent::editor_agent_read_skill,
        api::script_editor::agent::editor_agent_create_conversation,
        api::script_editor::agent::editor_agent_list_conversations,
        api::script_editor::agent::editor_agent_delete_conversation,
        api::script_editor::agent::editor_agent_rename_conversation,
        api::script_editor::agent::editor_agent_get_messages,
        api::script_editor::agent::editor_agent_clear_conversation,
        api::script_editor::agent::editor_agent_start_chat,
        api::script_editor::agent::editor_agent_stop_chat,
        api::script_editor::agent::editor_agent_rewind,
        api::script_editor::agent::editor_agent_resolve_approval,
        api::pet::update_solid_regions,
        api::pet::set_pet_mode,
        api::pet::set_bubble_side,
        api::schedule::get_schedules,
        api::schedule::save_schedules,
        api::schedule::reload_proactive_system,
        api::proactive_set_can_deliver,
        api::tool_settings::get_tool_settings,
        api::tool_settings::get_tool_runtime_info,
        api::tool_settings::save_tool_settings,
        api::tool_settings::test_web_search,
        api::tool_settings::get_tool_elevation_status,
        api::tool_settings::restart_tool_process_as_admin,
        api::tool_settings::resolve_command_approval,
        api::tool_settings::resolve_file_change_approval,
        api::tool_settings::resolve_file_delete_approval,
        api::achievement::get_achievement_list,
        api::achievement::unlock_achievement,
        api::adventure::list_character_adventures,
        api::adventure::list_all_adventures,
        api::adventure::start_adventure,
        api::adventure::check_adventure_unlocks,
        api::adventure::reset_adventure,
        api::workshop::fetch_discussions,
        resource_sync::check_resource_sync,
        resource_sync::apply_resource_sync,
        resource_sync::get_data_version,
        lan_sync::lan_sync_start_server,
        lan_sync::lan_sync_stop_server,
        lan_sync::lan_sync_scan_peers,
        lan_sync::lan_sync_plan_push,
        lan_sync::lan_sync_execute_push,
        lan_sync::lan_sync_plan_pull,
        lan_sync::lan_sync_execute_pull,
        lan_sync::lan_sync_restart,
        // ── 投屏（Screen Cast）──
        cast::cast_open_window,
        cast::cast_close_window,
        cast::cast_start,
        cast::cast_stop,
        cast::cast_get_status,
        cast::cast_get_snapshot,
        cast::cast_emit_mirror,
        cast::cast_get_mirror,
        cast::cast_play_voice,
        utils::cpu_perf::get_cpu_info,
        utils::cpu_perf::redetect_cpu,
        utils::gpu_perf::get_gpu_info,
        utils::gpu_perf::redetect_gpu,
        utils::gpu_perf::grade_active_gpu,
        api::role_archive::import_role,
        api::role_archive::import_role_from_path,
        api::role_archive::cancel_role_import,
        api::role_archive::rescan_roles,
        api::role_archive::export_role,
        api::role_archive::export_role_to_path,
        // 本地 TTS 相关命令
        ai_service::tts::local::tts_local_status,
        ai_service::tts::local::tts_local_list_catalog,
        ai_service::tts::local::tts_local_list_installed,
        ai_service::tts::local::tts_local_import_from_path,
        ai_service::tts::local::tts_local_download,
        ai_service::tts::local::tts_local_delete_voice,
        ai_service::tts::local::tts_local_delete_deberta,
        ai_service::tts::local::tts_local_import_style_vectors,
        ai_service::tts::local::tts_local_synthesize_preview,
        ai_service::tts::local::tts_local_get_enabled,
        ai_service::tts::cloud::commands::cosyvoice_get_config,
        ai_service::tts::cloud::commands::cosyvoice_save_api_key,
        ai_service::tts::cloud::commands::cosyvoice_create_voice,
        ai_service::tts::cloud::commands::cosyvoice_voice_status,
        ai_service::tts::cloud::commands::cosyvoice_list_voices,
        ai_service::tts::cloud::commands::cosyvoice_delete_voice,
        ai_service::tts::cloud::commands::cosyvoice_synthesize_preview,
        ai_service::tts::local::tts_local_set_enabled,
        // 推理设备选择：获取当前设备 / 枚举可用设备 / 切换设备
        ai_service::tts::local::tts_local_get_device,
        ai_service::tts::local::tts_local_list_devices,
        ai_service::tts::local::tts_local_set_device,
        // ASR 相关命令
        api::asr::asr_start_listening,
        api::asr::asr_stop_listening,
        api::asr::asr_vad_process_chunk,
        api::asr::asr_recognize_wav,
        api::asr::asr_recognize_wav_stream,
        api::asr::asr_cancel,
        api::asr::asr_list_providers,
        api::asr::asr_list_models,
        api::asr::asr_get_settings,
        api::asr::asr_set_settings,
        api::asr::asr_get_status,
        api::asr::asr_ptt_global_set_active,
        api::asr::asr_test_provider,
        api::asr::asr_start_streaming,
        api::asr::asr_stream_audio_chunk,
        api::asr::asr_stop_streaming,
        api::asr::asr_cancel_streaming,
        exit_app,
    ])
}

/// 前端确认关闭后调用，终止整个 Tauri 进程。
#[tauri::command]
fn exit_app(app: tauri::AppHandle) {
    app.exit(0);
}
