[profile.dev]
debug = 1
strip = "debuginfo"
split-debuginfo = "unpacked"
lto = false
opt-level = 0

[profile.release]
lto = "thin"
codegen-units = 16
panic = "abort"
strip = true
opt-level = "z"

[target.aarch64-linux-android]
rustflags = [
    "-C",
    "link-arg=-Wl,--allow-shlib-undefined",
    "-C",
    "link-arg=-Wl,--unresolved-symbols=ignore-all",
]
